backend:
  name: git-gateway
  branch: master

media_folder: static/assets
public_folder: assets

collections:
  - label: Videos
    name: videos
    folder: videos
    create: true
    fields:
      - { name: title, label: Title }
      - { name: description, label: Description, widget: markdown }
      - { name: url, label: Url}
  - label: Barbers
    name: barbers
    folder: barbers
    create: true
    fields:
      - { name: name, label: Name }
      - { name: bio, label: Bio, widget: markdown }
      - { name: pics, label: Pics, widget: image}
      - { name: links, label: Links}
  - label: Seamoss
    name: clients
    folder: seamoss_clients
    create: true
    fields:
      - { name: name, label: Name }
      - { name: bio, label: Bio, widget: markdown }
      - { name: links, label: Links}
  - label: "Gallery Image"
    name: gallery
    folder: gallery
    create: true
    identifier_field: imageTitle
    widget: "list"
    fields:
      - { label: Image, name: image, widget: image }
      - { label: "Image Title", name: imageTitle, widget: string }
  - label: Page Content
    name: content
    folder: content
    create: true
    fields:
      - { name: paragraphOne, label: Paragraph One }
      - { name: paragraphTwo, label: Paragraph Two }
  